CREATE TABLE IF NOT EXISTS public.persons (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    surname varchar(255) NOT NULL,
    age int NOT NULL,
    phone_number varchar(255),
    city_of_living varchar(255),
    PRIMARY KEY (id)
);