INSERT INTO AUTHORITY(ID, NAME) VALUES (1, 'READ');
INSERT INTO AUTHORITY(ID, NAME) VALUES (2, 'WRITE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (3, 'UPDATE');
INSERT INTO AUTHORITY(ID, NAME) VALUES (4, 'DELETE');
